import { InternalStudyType } from "@/types/studyTypes";

export const defaultStudy: InternalStudyType = {
    _id: "",
    sub_status: "",
    Conditions: [],
    Status: ["RECRUITING"],
    Contacts: [{ email: "", name: "", phone: "", role: "" }],
    Description: "",
    HasPublishedResults: false,
    Interventions: [{
      explanation: "",
      interventionType: "",
      description: "",
      label: "",
    }],
    InterventionNames: [],
    Researchers: [{
      name: "",
      affiliation: "",
      role: "",
    }],
    Keywords: [],
    Location: [{
      Facility: "",
      City: "",
      State: "",
      Country: "",
      Status: "RECRUITING",
    }],
    Restrictions: "",
    Sponsor: "",
    Title: "",
    Organization: "",
    StartDate: "",
    endDate: "",
    Phase: [],
    HealthyVolunteers: true,
    Sex: "",
    MinimumAge: "",
    MaximumAge: "",
    FunderType: "",
    PrimaryCompletionDate: "",
    LastUpdatePostDate: "",
    StudyType: "",
};