name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./clinicai-front
        run: npm install

      - name: Build application
        working-directory: ./clinicai-front
        run: npm run build

      - name: Deploy to Vercel
        working-directory: ./clinicai-front
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: npx vercel --token=$VERCEL_TOKEN --prod --yes